### ISSUE TITLE
OSError: Cant allocate memory

### ISSUE THREAD

**Issue by sunn-e** [fdjingyuan/Deep-Fashion-Analysis-ECCV2018#5]
Hi, I tried to rearrange files in the folder since they were giving issues with python -n src.train a--conf src.conf.lm.py  After rearrangement and approriate code run, I got this error

> (pytorch) l@l-Predator-G3-571:~/Deep-Fashion-Analysis-ECCV2018/src$ python -m train --conf lm
('override', 'MODEL_NAME', 'lm.pkl')
('override', 'LM_SELECT_VGG_CHANNEL', 512)
('override', 'WEIGHT_LOSS_LM_POS', 10)
('override', 'USE_NET', <class 'lm_networks.LandmarkExpNetwork'>)
('override', 'EVALUATOR', <class 'utils.LandmarkEvaluator'>)
('override', 'LM_SELECT_VGG_SIZE', 28)
('override', 'LEARNING_RATE_DECAY', 0.8)
('override', 'LM_SELECT_VGG', 'conv4_3')
('override', 'DATASET_PROC_METHOD_TRAIN', 'BBOXRESIZE')
('override', 'DATASET_PROC_METHOD_VAL', 'BBOXRESIZE')
('override', 'gaussian_R', 8)
('override', 'VAL_DIR', 'runs/lm/07-18 15:58:31')
('override', 'TRAIN_DIR', 'runs/lm/07-18 15:58:31')
('override', 'LM_BRANCH', <class 'lm_networks.LandmarkBranchUpsample'>)
Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /home/l/.cache/torch/checkpoints/vgg16-397923af.pth
100%|██████████| 553433881/553433881 [03:51<00:00, 2391934.54it/s]
Traceback (most recent call last):
  File "/home/l/miniconda2/envs/pytorch/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/l/miniconda2/envs/pytorch/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/l/Deep-Fashion-Analysis-ECCV2018/src/train.py", line 41, in <module>
    for i, sample in enumerate(train_dataloader):
  File "/home/l/miniconda2/envs/pytorch/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)
  File "/home/l/miniconda2/envs/pytorch/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 469, in __init__
    w.start()
  File "/home/l/miniconda2/envs/pytorch/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/home/l/miniconda2/envs/pytorch/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

My system has
*16GB DDR4 RAM. 
*GTX 1060 Ti 6GB version
*i7
*Ubuntu 16.04 lts
*cuda 10 with cudnn
* latest pytorch with python 2.7

I don't know whether it is because of insufficient memory or because of bad memory management. I think later is the case since there was no error  regarding the NN size that I kknow may arrive from CUDA insufficient memory. Let's see . Also I'm running this with python 2.7 so probably that could be an issue?

**Comment by sunn-e** [comment]
@fdjingyuan

**Comment by ashwath98** [comment]
Did you face this issue while creating the info.csv file?

I'm also getting a similar issue while running the code on colab
[tcmalloc: large alloc 2392449024 bytes]

**Comment by sunn-e** [comment]
Hi @ashwath98 , I never heard back from the author. I left it after little bit of tinkering. It's probably a bug. It would be great if you could create a new issues with log screenshots. That might get author's attention. You refer this issue there too. I would have really loved helping but I never got it working. Checkout other forks of the project. See if they work.

**Comment by ashwath98** [comment]
Sure. Will look into the forks.
Thanks
